version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL={DATABASE_URL}
      - SESSION_DIRECTORY=/app/sessions
      - WEBHOOK_URL=${WEBHOOK_URL}
      - ADMIN_USERNAME={ADMIN_USERNAME}
      - ADMIN_PASSWORD={ADMIN_PASSWORD}
      - JWT_SECRET={JWT_SECRET}
      - API_TOKEN={API_TOKEN}
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wa_baileys_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume
